name: Renovate
on: push
jobs:
  main:
    name: Run Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Renovate
        uses: djiit/action-renovate@master
        with:
          args: ${{ github.repository }}
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
