name: renovate

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: $GITHUB_REPOSITORY@master
        with:
          args: $GITHUB_REPOSITORY
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
